---
# using dnf in a shell because we want the power tools repo to be persistent for epel 
- name: enable power tool for epel
  shell: dnf config-manager --set-enabled PowerTools
  args:
     warn: false


- name: install epel via greeling's role 
  include_role:
          name: geerlingguy.repo-epel
          tasks_from: main
