---
- name: Add users
  user:
    name: '{{ item }}'
    groups: wheel
    state: present
  with_items:
    - gegorbet
    - demeler
    - alexey

- name: Add authorized keys
  authorized_key:
    user: '{{ item }}'
    key: "{{ lookup( 'file', '../files/{{ item }}') }}"
  with_items:
    - gegorbet
    - alexey
    - demeler
