---
- name: Get rpm package facts
  package_facts:
    manager: auto

- name: install slurm dependencies
  dnf:
        enablerepo: PowerTools
        name:
                - globus-gram-job-manager-slurm
                - munge-devel
                - munge
                - readline-devel
                - pam-devel
                - perl-ExtUtils-MakeMaker
                - perl-Switch
                - rpm-build
                - make
                - gcc
                - mariadb-devel
        state: present

- name: check if munge key already exists
  stat:
    path: /etc/munge/munge.key
  register: munge_key

- name: create munge key
  shell: "/usr/sbin/create-munge-key"
  when: munge_key.stat.exists == false
  notify:
    - restart munge

- name: get slurm source
  get_url:
        url: "https://download.schedmd.com/slurm/slurm-{{ slurm_ver }}.tar.bz2"
        dest: /tmp

- name: build slurm packages
  shell: "rpmbuild -ta /tmp/slurm-{{ slurm_ver }}.tar.bz2"
  when: "'slurm' not in ansible_facts.packages"


- name: install built packages
  shell: "yum install ./slurm*  -y"
  args:
        chdir: /root/rpmbuild/RPMS/x86_64
  when: "'slurm' not in ansible_facts.packages"

- name: Create slurm user
  user:
        name: slurm
        state: present
        system: yes

- name: create slurm log dir
  file:
        path: /var/log/slurm/
        owner: slurm
        group: slurm
        state: directory

- name: create slurm spool dir
  file:
        path: /var/spool/slurm
        owner: slurm
        group: slurm
        state: directory

- name: config slurm.conf
  template:
        src: slurm.conf.j2
        dest: /etc/slurm/slurm.conf
        backup: yes
  notify:
        - restart slurmd
        - restart slurmctld
