---
language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
install:
  - pip install molecule docker
script:
  - env: config-lims-php 
    before_script: 
      - cd ./roles/config-lims-php
    script: 
      - molecule --version
      - ansible --version
      - molecule test
