---
language: python
services:
  - docker
install:
  - pip install molecule docker
env:
  global: 
    ROLE_NAME: 
      - config-lims-php

  matrix: 
    - MOLECULE_DISTRO: centos8


before_script: 
  - cd ${TRAVIS_BUILD_DIR}/roles/${ROLE_NAME} 
 
script: 
  - molecule test 

on:
  branch: master
