---
language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
install:
  - pip install molecule docker
script:
  - env: Php role 
    before_script: 
      - cd ${TRAVIS_BUILD_DIR}/roles/config-php
    script: 
      - molecule --version
      - ansible --version
      - molecule test
