---
language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
install:
  - pip install molecule docker

matrix: 
  include: 
    - env: config-lims-php
      before_script: 
        - cd ${TRAVIS_BUILD_DIR}/roles/config-lims-php
      script: 
        - molecule --version
        - ansible --version
        - molecule test
on:
  branch: master
