---
# playbook for installing a new cluster
- hosts: demeler1host
# uncomment if running on localhost
#  connection: local
  
  gather_facts: yes
  
  pre_tasks:

  roles:
#      - build-qt-cluster
      - build-us-mpi-cluster
     
  vars:
      - qt_force_rebuild           : true
      - rebuild_us_mpi             : true
      - target_dir                 : /home/usadmin/perftest
      - qt_dir                     : /opt
      - extra_configs              : "-no-gui -no-pch"
      - compiler                   : "icc"
      - qmake_cc                   : "icc"
      - qmake_cxx                  : "icpc"
      - qmake_link                 : "icpc"
      - mpi_path                   : "/usr/lib64/mpich"
      - mpi_libs                   : "-L{{ mpi_path }}/lib -lmpi"
      - include_path               : "/usr/include/mpich-x86_64"
      - cores_performance          : 16
      
      - module_loads              : "module purge; module load ultrascan/mpi-build; . /opt/intel/oneapi/setvars.sh; module load mpi"
      - platform                   : "linux-icc-64"
      - comp_opt                   : "-O3 -march=native"
      - cores_for_parallel_compile : 3
      - qt_major_version           : "5.14"
      - qt_version                 : "5.14.2"
      - qwt_version                : "6.1.5"
      - us3_branch                 : "master"
      - slurm_cores                : 128
      - slurm_sbatch_extras        : ""

      - mpirun                     : "mpirun"
      - queue                      : "batch"
      