---
- hosts: example-host
  remote_user: usadmin

  pre_tasks:
# uncomment to get all ansible_facts for target host
#      - name: Print all available facts
#        ansible.builtin.debug:
#          var: ansible_facts

      - name: set www_user for Debian
        set_fact:
          www_user: "www-data"
        when: ansible_os_family == "Debian"

      - name:  set www_user for RedHat
        set_fact:
          www_user: "apache"
        when: ansible_os_family == "RedHat"

      - name: disable selinux
        selinux:
           state: disabled

      - name: update system
        yum: name=* state=latest
        when: ansible_facts['os_family'] == "RedHat"

      - name: install EPEL repo for CentOS
        yum: name=epel-release state=present
        when: ansible_facts['distribution'] == "CentOS"

      - name: enable codeready for RedHat
        command:
           cmd: subscription-manager repos --enable "codeready-builder-for-rhel-8-x86_64-rpms"
        when: ansible_facts['distribution'] == "RedHat"

      - name: enable codeready for Oracle
        command:
           cmd: dnf config-manager --set-enabled ol8_codeready_builder
        when: ansible_facts['distribution'] == "OracleLinux"

      - name: install EPEL repo for RedHat
        yum:
           name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
           state: present
        when: ansible_facts['distribution'] == "RedHat" or ansible_os_family == "Rocky" or ansible_facts['distribution'] == "OracleLinux"

      - name: set powertools / crb
        set_fact:
          powertools: "crb"
        when: ansible_facts['distribution_major_version'] == '9'

      - name: set powertools / crb
        set_fact:
          powertools: "powertools"
        when: ansible_facts['distribution_major_version'] == '8'

      - name: set user_home
        set_fact:
          user_home: "/home"
        when: user_home is undefined

  roles:
      - config-lims-gui
      - config-lims-admin
      - config-lims-firewall
      - config-lims-repo
      - config-lims-us3-user
      - config-lims-database
      - config-lims-apache
      - config-lims-php
      - config-lims-lims
      - config-lims-slurm
      - build-qt
      - build-qwt
      - build-us3
      - build-mpich
      - build-us-mpi
      - install-vncserver
      - install-postfix
      - install-chrony
      - install-google-fonts
      - install-msttcore-fonts
      - install-reverse-tunnel-service
      - renice-mariadb
      - renice-slurmd
      - restart-php-fpm
      - install-demo-dbinst
      - config-lims-backup
      - install-xrdp
      - install-proxychains4
#optional    - install-fail2ban
#scigap-only - config-lims-scigap
      - config-authentication-messages
      
  become: yes
  vars:
        - user_home:           "/home"
        - install_workstation: false
        - install_commercial:  true
        - NO_LIMS:             false

        # set the desired compiler optimization
        # for hardware installs
        - comp_opt: "-march=native"
        # perhaps for VM installs if qt core dumps
        # - comp_opt: "-m64"
        
        # innodb_buffer_pool_size
        - innodb_buffer_pool_size: "2G"
        # - innodb_buffer_pool_size: "8G"

        # uncomment one of the below for default allowed submissions
        - submit_localonly: true
        # - submit_remoteonly : true
        # - submit_localandremote : true

        # Required variables to define:
        # N.B. once you set these, you can't change them simply by rerunning ansible-playbook for the same remote host!
        - us3_db_pass:       "foobar-demo"
        - root_db_pass:      "foobar-super"
        - admins_db_pass:    "foobar-admin"
        - gbl_db_pass:       "foobar-global"
        - us3php_db_pass:    "foobar-php"
        - limsadmin_db_pass: "foobar-iam-admin" 

        - admin_email:       "example@email.org"
        - cron_admin:        "example@email.org" # root@localhost 
        
        - ipaddr_ext:        "192.168.5.30"
        - ipaddr_int:        "192.168.5.30"
        
        - self_signed: 'yes' # change to 'no' to use certbot 

        - qt_major_version:  "5.15"
        - qt_version:        "5.15.17"
        - qwt_version:       "6.1.6"
        - cores_for_parallel_compile: "{{ ansible_processor_vcpus }}"
        - us3_branch:        "release-2025-Q1"
        - sql_branch:        "release-2025-Q1"
        - dbinst_branch:     "release-2025-Q1"
        - gridctl_branch:    "release-2025-Q1"
        - common_branch:     "release-2025-Q1"
        - newinst_branch:    "release-2025-Q1"
        - webinfo_branch:    "release-2025-Q1"
        - airavata_branch:   "meta-scheduler-prod"
        - utils_branch:      "main"

        - postfix_relay_smtp_host: smtp.gmail.com
        - postfix_relay_smtp_port: 587
        - postfix_relay_smtp_user: us.etc.tests@gmail.com
        - postfix_relay_smtp_password: put_app_password_here

        # required for role install-reverse-tunnel-service
        # you will manually need to install usadmin's public key on the rtunnel_user @ rtunnel_ip's authorized keys
        - rtunnel_user: "ultrascan"
        - rtunnel_ip: "secure.aucsolutions.com"
        # assign unique port (if both rtunnel & rtunnel service installed, use different ports!
        - rtunnel_service_port: "220XX"
        # any extra command options required to ssh, e.g. "-J user@jumpserver" etc.
        - rtunnel_service_ssh_extras: ""
        ## enabled at boot up - "no" or "yes"
        - rtunnel_service_enabled: "yes"
        ## current state -  "started" or "stopped" 
        - rtunnel_service_state: "started"

        # set this to a specific value (could be numeric ip) instead of {{ ansible_fqdn }} if you with, e.g. if the host is private
        # N.B. you can only configure one host per ansible-playbook run if you do not use {{ ansible_fqdn }}
        - hostname: "{{ ansible_fqdn }}"
        - postfix_hostname: "{{ hostname }}"
        # N.B. if your host name is pure ip (e.g. 1.2.3.4 etc), you need to configure a text string prefix as commented below
        # - postfix_hostname: "us-{{ hostname }}"

        # Doesn't matter if self-signed is enabled but here as an example for some certbot uses
        - certbot_create_if_missing: true
        - certbot_admin_email: "{{ admin_email }}" 
        - certbot_create_standalone_stop_services: [httpd] # centos/RHEL 
        - certbot_certs: 
            - domains: 
                  - "{{ hostname }}" 

        - certbot_auto_renew: true 
        - certbot_auto_renew_hour: "1" 
        - certbot_auto_renew_minute: "30" 
        - cerbot_auto_renew_options: "--quiet --no-self-upgrade"

        - slurm_ver: 20.11.9 # Change to appropriate version
        - slurm_md5: 79b39943768ef21b83585e2f5087d9af

        # N.B. slurm_cores can not exceed available cores, if it does, the node will be stuck "draining" (waiting for available resources)
        #      if you want to develop (not production!) on a smaller system
        #         add "#SBATCH -O" to your sbatch submission scripts to allow overcommitting
        #         set - slurm_sbatch_extras : "#SBATCH -O\n" for slurm testing scripts via ansible
        - slurm_cores : "{{ ansible_processor_vcpus }}"
        - slurm_sbatch_extras : ""
        # - slurm_sbatch_extras : "#SBATCH -O\n"

        # Overrride variables that are default
        - lims_admin: "John Smith"
        - org_name: "Ultrascan Example LIMS"

