---
# initial upgrade playbook, carefully add capabilities
- hosts:        example-host
  gather_facts: yes
  remote_user:  usadmin
  become:       yes
  
  pre_tasks:
#  - name: System details
#    debug: msg="{{ item }}"
#    with_items:
#      - "{{ ansible_os_family }}"
#      - "{{ ansible_distribution }}"
#      - "{{ ansible_distribution_version }}"
#      - "{{ ansible_distribution_major_version }}"

  - shell: grep QTDIR /etc/modulefiles/ultrascan/gui-build | awk -F- '{ print $2 }'
    register: qtinfo

  - name: set facts
    set_fact:
      qt_version: "{{ qtinfo.stdout_lines[0] }}"
      os_version: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  - debug: msg="os_version {{ os_version }}\nqt_version {{ qt_version }}"

  - shell: 'for j in /opt/ultrascan3 /srv ~us3; { for i in `find $j -name "*.git" | sed s/.git$//`; { (printf "%-50s" "$i" && cd $i && RDATE=`git log -1 --shortstat .|grep Date:|sed -e "s/Date:   //"` && SHASH=`git log -1 --oneline .| cut -d" " -f1` && RNUMB=`git log --oneline | sed -n "/$SHASH/,99999p" | wc -l` && printf "%-30s revision %d\n" "$RDATE" $RNUMB) }; }'
    register: gitversions
  - debug: var=gitversions.stdout_lines


  roles:

  vars:

