---
# initial upgrade playbook, carefully add capabilities
- hosts:        allknownhosts
  gather_facts: yes
  remote_user:  usadmin
  become:       yes
  
  pre_tasks:
#  - name: System details
#    debug: msg="{{ item }}"
#    with_items:
#      - "{{ ansible_os_family }}"
#      - "{{ ansible_distribution }}"
#      - "{{ ansible_distribution_version }}"
#      - "{{ ansible_distribution_major_version }}"

  - shell: grep QTDIR /etc/modulefiles/ultrascan/gui-build | awk -F- '{ print $2 }'
    register: qtinfo

  - shell: grep QWTDIR /etc/modulefiles/ultrascan/gui-build | awk -F- '{ print $3 }'
    register: qwtinfo

  - name: set facts
    set_fact:
      qt_version:  "{{ qtinfo.stdout_lines[0] }}"
      qwt_version: "{{ qwtinfo.stdout_lines[0] }}"
      os_version:  "{{ ansible_distribution }} {{ ansible_distribution_version }}"
  - debug: msg="os_version {{ os_version }}\nqt_version {{ qt_version }}\nqt_version {{ qwt_version }}"

  - shell: 'for j in /opt/ultrascan3 /srv ~us3; { for i in `find $j -name "*.git" | sed s/.git$//`; { (printf "%-70s" "$i" && cd $i && RDATE=`git log -1 --shortstat .|grep Date:|sed -e "s/Date:   //"` && SHASH=`git log -1 --oneline .| cut -d" " -f1` && RNUMB=`git log --oneline | sed -n "/$SHASH/,99999p" | wc -l` && LCHNG=`git status -s | grep "^ M" | wc -l` && printf "%-30s  revision: %-6d tracked files with changes: %d\n" "$RDATE" $RNUMB $LCHNG ) }; }'
    register: gitversions
  - debug: var=gitversions.stdout_lines

  roles:
    - upgrade-environment-modules

  vars:
    us3_path:          "/home/us3"
    us3_nodb_path:     "{{ us3_path }}/us3-nodb"
    us3_cluster_path:  "{{ us3_path }}/cluster"

