---
# tasks file for renice-mariadb

- name: copy nice.conf to /etc/systemd/system/mariadb.service.d
  ansible.builtin.copy:
    src: nice.conf
    dest: /etc/systemd/system/mariadb.service.d/nice.conf
    owner: root
    group: root
    mode: '0644'

- name: reload systemd daemon
  systemd:
       daemon_reload: yes

- name: restart MariaDB
  service:
       name: mariadb
       enabled: yes
       state: restarted
