---
- set_fact:
    user_home: "/home"
  when: user_home is undefined

# We do this because no default passwords are supplied
- name: assert password variables are defined
  assert:
     that:
       - us3_db_pass is defined
       - gbl_db_pass is defined
       - admins_db_pass is defined
#       - root_db_pass is defined
       - limsadmin_db_pass is defined

# Create ini file
- name: Create LIMS ini file
  template:
      src: ini-template.j2
      dest: "{{ ini_cfg_path }}"
      owner: us3
      group: "{{ www_user }}"
      mode: "0640"

- name: Run LIMS related tasks
  include: lims-tasks.yml
  when: NO_LIMS is undefined or NO_LIMS == false or NO_LIMS == ''

