---
- name: Create newus3 database
  mysql_db:
        name: newus3
        state: present
        login_user: root
        login_password: "{{ root_db_pass }}"

- name: Create global database
  mysql_db:
        name: "{{ gbl_db_name }}"
        state: present
        login_user: root
        login_password: "{{ root_db_pass }}"

- name: Copy over the metadata_create file
  copy:
        src: metadata_create.sql
        dest: /tmp
  when: root_pwd_check.rc == 0

- name: Inject metadata file for newus3
  mysql_db:
        login_user: root
        login_password: "{{ root_db_pass }}"
        name: newus3
        state: import
        login_host: localhost
        target: /tmp/metadata_create.sql
  when: root_pwd_check.rc == 0

- name: Copy over the people_create file
  copy:
        src: people_create.sql
        dest: /tmp
  when: root_pwd_check.rc == 0

- name: Inject the people_create file
  mysql_db:
        login_user: root
        login_password: "{{ root_db_pass }}"
        name: newus3
        state: import
        target: /tmp/people_create.sql
  when: root_pwd_check.rc == 0

- name: Copy over the gfac file
  copy:
        src: gfac-db.sql
        dest: /tmp
  when: root_pwd_check.rc == 0

- name: Inject gfac-db file for gfac
  mysql_db:
        login_user: root
        login_password: "{{ root_db_pass }}"
        name: gfac
        state: import
        target: /tmp/gfac-db.sql
  when: root_pwd_check.rc == 0

  # insert default admins for newus3_db
- name: Create a temp people sql file for dumping admins to newus3 database
  template:
          src: new_people_inject.sql.j2
          dest: /tmp/new_people_inject.sql
  when: root_pwd_check.rc == 0

- name: Inject the temp people sql file
  mysql_db:
        login_user: root
        login_password: "{{ root_db_pass }}"
        name: newus3
        state: import
        target: /tmp/new_people_inject.sql
  when: root_pwd_check.rc == 0

- name: Clean up tmp people sql file
  file :
        path: /tmp/new_people_inject.sql
        state: absent
  when: root_pwd_check.rc == 0
