---
# tasks file for config-lims-gui

- name: groupinstall workstation
  command: dnf groupinstall workstation
  when: install_workstation|default(false)
  
- name: Create a directory /etc/skel/.local/share/applications
  file:
    path: /etc/skel/.local/share/applications
    state: directory
    mode: '0755'

- name: install ultrascan & us_somo desktop icons
  template: 
    src: "{{ item }}.j2"
    dest: /etc/skel/.local/share/applications/{{ item }}
    mode: '0755'
  with_items:
    - ultrascan.desktop
    - us_somo.desktop

- name: setup gnome default favorites
  copy:
    src: 00-favorite-apps
    dest: /etc/dconf/db/local.d/00-favorite-apps
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root


- name: update dconf database
  command: dconf update
  