---
# 1009 was picked just to follow the uid on demeler3
- set_fact:
    user_home: "/home"
  when: user_home is undefined

- name: install dependencies RedHat
  dnf:
    name:
      - git
      - httpd
      - php
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Rocky"

- name: install dependencies Debian
  apt:
    name:
      - git
      - apache2
      - php
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Create group for us3
  group:
    name: us3
    state: present

- name: Create the ultrascan3 user
  user:
    name: us3
    comment: ultrascan3 system user
    group: us3
    shell: /bin/bash
    state: present

- name: make {{ user_home }}/us3/lims/database/sql safe
  shell:
    cmd: "git config --global --add safe.directory {{ user_home }}/us3/lims/database/sql"

- name: git clone us3_mysql repository
  git:
   repo: https://github.com/ehb54/us3_sql.git
   version: "{{ sql_branch }}"
   dest: "{{ user_home }}/us3/lims/database/sql"

- name: make {{ user_home }}/us3/lims/database/utils safe
  shell:
    cmd: "git config --global --add safe.directory {{ user_home }}/us3/lims/database/utils"

- name: git clone us3lims_dbutils repository
  git:
   repo: https://github.com/ehb54/us3lims_dbutils.git
   version: "{{ utils_branch }}"
   dest: "{{ user_home }}/us3/lims/database/utils"

- name: Change ownership of us3lims_dbutils
  ansible.builtin.file:
    path: "{{ user_home }}/us3/lims/database/utils"
    state: directory
    recurse: yes
    owner: us3
    group: us3

- set_fact:
    gridctl_branch: "{{ branch }}"
  when: gridctl_branch is undefined
    
- name: make {{ user_home }}/us3/lims/database/utils safe
  shell:
    cmd: "git config --global --add safe.directory {{ user_home }}/us3/lims/bin"

- name: git clone gridctl repository to bin
  git:
   repo: https://github.com/ehb54/us3lims_gridctl.git
   version: "{{ gridctl_branch }}"
   dest: "{{ user_home }}/us3/lims/bin"

- name: Change permissions in gridctl
  file:
      path: "{{ user_home }}/us3/lims/bin"
      state: directory
      recurse: yes
  changed_when: false

- name: template listen-config.php
  template:
    src: listen-config.php.j2
    dest: "{{ user_home }}/us3/lims/bin/listen-config.php"
    
- name: Set us3 ownership of us3/lims/bin
  command:
    chdir: "{{ user_home }}/us3/lims/bin"
    cmd: chown -R us3:us3 .
    warn: false

- name: Create us3/etc
  file:
    path: "{{ user_home }}/us3/lims/etc"
    state: directory
    owner: us3
    group: us3

- name: Run LIMS related tasks
  include: lims-tasks.yml
  when: NO_LIMS is undefined or NO_LIMS == false or NO_LIMS == ''
