---
# 1009 was picked just to follow the uid on demeler3
- name: Create group for us3
  group:
    name: us3
    state: present

- name: Create the ultrascan3 user
  user:
    name: us3
    comment: ultrascan3 system user
    group: us3
    shell: /bin/bash
    state: present

- name: check if lims instance folder exist
  stat:
    path: /home/us3/lims/database/instances
  register: instance_folder

- name: create instances folder
  file:
    path: '/home/us3/lims/database/instances'
    state: directory
    owner: us3
    group: apache
  when: instance_folder.stat.exists == false

- name: git mysql scripts
  git:
   repo: https://github.com/ehb54/us3_sql.git
   version: "{{ branch }}"
   dest: "/home/us3/lims/database/sql"

- name: git gridctl scripts
  git:
   repo: https://github.com/ehb54/us3lims_gridctl.git
   version: "{{ branch }}"
   dest: "/home/us3/lims/bin"

# - name: Ensure correct permissions in LIMS for us3 user
#   file:
#     path: "/home/us3/lims"
#     owner: "us3"
#     group: "us3"
#     recurse: yes
#     state: directory
