---
# 1009 was picked just to follow the uid on demeler3
- name: install dependencies
  dnf:
    name:
      - git
      - httpd

- name: Create group for us3
  group:
    name: us3
    state: present

- name: Create the ultrascan3 user
  user:
    name: us3
    comment: ultrascan3 system user
    group: us3
    shell: /bin/bash
    state: present

- name: check if lims instance folder exists
  stat:
    path: /home/us3/lims/database/instances
  register: instance_folder

- name: create instances folder
  file:
    path: '/home/us3/lims/database/instances'
    state: directory
    owner: us3
    group: apache
  when: instance_folder.stat.exists == false

- name: check if work folder exists
  stat:
    path: /home/us3/lims/work
  register: work_folder

- name: create work folder
  file:
    path: '/home/us3/lims/work'
    state: directory
    owner: us3
    group: apache
  when: work_folder.stat.exists == false

- name: git mysql scripts
  git:
   repo: https://github.com/ehb54/us3_sql.git
   version: "{{ branch }}"
   dest: "/home/us3/lims/database/sql"

- name: git gridctl scripts
  git:
   repo: https://github.com/ehb54/us3lims_gridctl.git
   version: "{{ branch }}"
   dest: "/home/us3/lims/bin"

- name: template listen-config.php
  template:
    src: listen-config.php.j2
    dest: /home/us3/lims/bin/listen-config.php

- name: Check if us3/lims/etc folder exists
  stat:
    path: /home/us3/lims/etc
  register: etc_folder

- name: Create us3/etc
  file:
    path: /home/us3/lims/etc
    state: directory
  when: etc_folder.stat.exists == false

- name: check if us3-pipe exists
  stat:
    path: /home/us3/lims/etc/us3-pipe
  register: us3pipe

- name: Create us3-pipe
  shell:
    cmd: mkfifo /home/us3/lims/etc/us3-pipe
  when: us3pipe.stat.exists == false

# https://habilis.net/cronic/
- name: Copy over cronic script
  copy:
    src: cronic
    dest: /usr/bin/cronic
    mode: '0755'
    owner: root
    group: root

- name: Set Cron Admin
  cron:
    name: MAILTO
    env: yes
    job: "{{ cron_admin }}"

- name: Set gridctl_pro cronjob
  cron:
    name: gridctl_pro cronjob
    minute: "*/1"
    job: /usr/bin/cronic php /home/us3/lims/bin/gridctl_pro.php
    user: us3
  when: cron_enable_pro == 'yes'

- name: set gridctl_dev cronjob
  cron:
    name: gridctl_dev cronjob
    minute: "*/1"
    job: /usr/bin/cronic php /home/us3/lims/bin/gridctl_dev.php
    user: us3
  when: cron_enable_dev == 'yes'

- name: set cluster_status cronjob
  cron:
    name: cluster_status cronjob
    minute: "*/12"
    job: /usr/bin/cronic php /home/us3/lims/bin/cluster_status.php
    user: us3

- name: set update_notice cronjob
  cron:
    name: update_notice cronjob
    minute: "*/20"
    job: /usr/bin/cronic php /home/us3/lims/bin/update_notice.php
    user: us3
  when: cron_enable_update_notice == 'yes'

- name: Copy over us3-listen.service
  copy:
    src: us3-listen.service
    dest: /etc/systemd/system/us3-listen.service
