---
# tasks file for build-us-mpi

- name: Check if us-mpi already installed, using {{ us3_cluster_path }}/bin/us_mpi_analysis as a proxy
  stat: 
    path: "{{ us3_cluster_path }}/bin/us_mpi_analysis"
  register: us_mpi_installed_details

- name: Install, configure and compile us_mpi_analysis
  block:
    - name: Git clone ultrascan3 repository
      git:
       repo: https://github.com/ehb54/ultrascan3.git
       version: "{{ us3_branch }}"
       dest: "{{ us3_nodb_path }}"

    - name: Create {{ us3_cluster_path }} directories
      file: 
        path: "{{ us3_cluster_path }}/{{ item }}"
        mode: '0755'
        state: directory
      with_items:
        - 
        - bin
        - lib

    - name: Copy over template files for building us-mpi
      template: 
        src: "{{ item.name }}.j2"
        dest: "{{ us3_nodb_path }}/{{ item.name }}"
        mode: "{{ item.mode }}"
      with_items:
        - { name: local.pri, mode: '0644' }
        - { name: make-uma, mode: '0755' }

    - name: Clean up build.stdout, .stderr
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ us3_nodb_path }}/build.stdout"
        - "{{ us3_nodb_path }}/build.stderr"

    - name: make us_mpi_analysis
      shell:
        chdir: "{{ us3_nodb_path }}"
        cmd: ./make-uma {{ item }} >> build.stdout 2>> build.stderr
      with_items:
        - update
        - build
        - install

  when: us_mpi_installed_details.stat.exists == false

- name: Test mpi
  block:
  - name: Empty {{ mpi_test_path }} directories
    file: 
      path: "{{ mpi_test_path }}/{{ item }}"
      state: absent
    with_items:
      - mpi
      - slurm
      - analysis

  - name: Create {{ mpi_test_path }} directories
    file: 
      path: "{{ mpi_test_path }}/{{ item }}"
      mode: '0755'
      state: directory
    with_items:
      - 
      - mpi
      - slurm
      - analysis
        
  - name: Copy over template files for mpi tests
    template: 
      src: "{{ item.name }}.j2"
      dest: "{{ mpi_test_path }}/{{ item.subdir }}/{{ item.name }}"
      mode: '0755'
    with_items:
      - { name: testmpi.sh, subdir: mpi }
      - { name: testslurm.sh, subdir: slurm }
      - { name: testanalysis.sh, subdir: analysis }

  - name: Copy over non-template files for mpi tests
    copy: 
      src: "{{ item.name }}"
      dest: "{{ mpi_test_path }}/{{ item.subdir }}/{{ item.name }}"
      mode: '0644'
    with_items:
      - { name: hpcinput-localhost-uslims3_test-00001.tar.xz, subdir: analysis }

