#- name: install apache
#  package:
#    name:
#      - httpd
#      - mod_ssl
        #update_cache: yes

- name: Use Rhel tasks
  include: redhat-tasks.yml
  when: " ansible_distribution  == 'Redhat' or ansible_distribution == 'CentOS'"

  #- name: debug
  #debug: msg="{{ ansible_distribution_version }}"

- name: Use Debian tasks
  include: debian-tasks.yml
  when: " ansible_distribution  == 'Debian'"

- name: Ensure www path exists
  file:
        path: "{{ www_base }}"
        owner: us3
        group: "{{ www_user }}"
        state: directory

- include_role:
         name: geerlingguy.certbot
  when: self_signed == 'no'

- name: Create ssl folder for self-signed cert
  file:
        path: "{{ ssl_self_base_path }}"
        state: directory
  when: self_signed == 'yes'

- name: generate the self-signed private key
  openssl_privatekey:
        path: "{{ ssl_self_key_path }}"
  when: self_signed == 'yes'

- name: generate the self-signed csr
  openssl_csr:
        path: "{{ ssl_self_csr_path }}"
        privatekey_path: "{{ ssl_self_key_path }}"
  when: self_signed == 'yes'

- name: Generate self signed ssl
  openssl_certificate:
        provider: selfsigned
        path: "{{ ssl_self_cert_path }}"
        privatekey_path: "{{ ssl_self_key_path }}"
        csr_path: "{{ ssl_self_csr_path }}"
  when: self_signed == 'yes'
