---
# tasks file for config-lims-backup

- name: Check if db_config setup
  stat: 
    path: /home/us3/lims/database/utils/db_config.php
  register: db_config_details
  failed_when: not db_config_details.stat.exists

- name: make directory /srv/data directories if non existant
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: usadmin
    owner: usadmin
  loop:
    - /srv/data
    - /srv/data/sqldumps
    - /srv/data/log

- name: install in cronic
  ansible.builtin.lineinfile:
    path: /etc/crontab
    insertafter: EOF
    line: "# Ansible: daily backup\n10 0 * * * root /usr/bin/cronic php /home/us3/lims/database/utils/uslims_daily_backup.php"
